version: "3.8"
services:
  microphone:
    build: https://github.com/rhasspy/wyoming-mic-external.git
    restart: unless-stopped
    ports:
      - "10600:10600"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    command:
      - "--device"
      - "default:CARD=USB"
      - "--debug"
  playback:
    build: https://github.com/rhasspy/wyoming-snd-external.git
    restart: unless-stopped
    ports:
      - "10601:10601"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    command:
      - "--device"
      - "default:CARD=USB"
      - "--debug"
  wakeword:
    image: rhasspy/wyoming-openwakeword
    restart: unless-stopped
    ports:
      - "10400:10400"
    command:
      - "--debug"
      - "--preload-model"
      - ok_nabu
      # - --threshold # default: 0.5 (0.0-1.0)
      # - --trigger-level # default: 1
  satellite:
    build: https://github.com/rhasspy/wyoming-satellite.git
    restart: unless-stopped
    ports:
      - "10700:10700"
    command:
      - "--mic-uri"
      - "tcp://microphone:10600"
      - "--snd-uri"
      - "tcp://playback:10601"
      - "--wake-uri"
      - "tcp://wakeword:10400"
      - --wake-word-name
      - ok_nabu
      - --awake-wav
      - /app/sounds/awake.wav
      - --done-wav
      - /app/sounds/done.wav
      - "--name"
      - "Wyoming Satellite"
      - --debug
      - --debug-recording-dir
      - /debug-recording-dir
      # - --mic-noise-suppression # default: 0 -> 2?
      # - --mic-auto-gain # default: 0 -> 5?
    volumes:
      - ./satellite/debug-recording-dir:/debug-recording-dir
