services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1883:1883
    networks:
      - homelab
    user: "${UID}:${GID}"
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      # - PYTHON_FROZEN_MODULES=off # https://docs.python.org/3/using/cmdline.html#envvar-PYTHON_FROZEN_MODULES
    volumes:
      - ./homeassistant:/config
      - ./tmp:/config/tmp
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123 # Web UI
    #   - 5678:5678 # Debug
    privileged: true
    # user: "${UID}:${GID}"
    networks:
      - homelab
    cap_add:
      - NET_ADMIN
      - NET_RAW
  appdaemon:
    image: acockburn/appdaemon:latest
    container_name: appdaemon
    restart: unless-stopped
    volumes:
      - ./appdaemon:/conf
      - ./tmp:/conf/tmp
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5050:5050
    user: "${UID}:${GID}"
    networks:
      - homelab
  zwavejs:
    image: zwavejs/zwave-js-ui:11.3 # 11.4 is busted
    container_name: zwavejs
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./zwavejs:/usr/src/app/store
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8091:8091
      - 3001:3000
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_51300097-if00-port0:/dev/zwave
    user: "${UID}:${GID}"
    group_add:
      - dialout
    networks:
      - homelab
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_fa78108a5586ec11b33feb3719c2d21c-if00-port0:/dev/zigbee
    user: "${UID}:${GID}"
    group_add:
      - dialout
    networks:
      - homelab
  duckdns:
    image: lscr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=America/Los_Angeles
      - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped
    hostname: my-syncthing
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - ./syncthing:/var/syncthing
    ports:
      # - 3004:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      # - 21027:21027/udp # Receive local discovery broadcasts
    networks:
      - homelab
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
    ports:
      - 81:81 # Admin
      - 3002:3002 # Open WebUI
      - 8443:8443 # Home Assistant
      - 8384:8384 # Syncthing
      - 7860:7860 # Automatic
      - 11434:11434 # Ollama
      - 6680:6680 # mpd
      - 8888:8888 # searxng
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - homelab
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    hostname: open-webui
    environment:
      # https://docs.openwebui.com/getting-started/env-configuration/
      # General
      # - WEBUI_AUTH=0
      - ENABLE_SIGNUP=0
      - DEFAULT_MODELS=qwen2.5:32b
      # - RESET_CONFIG_ON_START=1
      # Ollama
      - OLLAMA_BASE_URL=http://mithras-pc:11434
      # OpenAI
      - ENABLE_OPENAI_API=0
      # RAG
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_EMBEDDING_ENGINE=ollama
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
      # Image
      - ENABLE_IMAGE_GENERATION=true
      - IMAGE_GENERATION_ENGINE=automatic1111
      - AUTOMATIC1111_BASE_URL=http://mithras-pc:7860
      - IMAGE_GENERATION_MODEL='sd-v1-5-inpainting.ckpt [c6bbc15e32]'
      # Audio
      - AUDIO_STT_ENGINE=openai
    volumes:
      - ./open-webui/data:/app/backend/data
    # ports:
    #   - 3003:8080 # Web UI
    networks:
      - homelab
  searxng:
    image: docker.io/searxng/searxng
    container_name: searxng
    restart: unless-stopped
    environment:
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
      SEARXNG_SECRET: ${SEARXNG_SECRET}
    volumes:
      - ./searxng:/etc/searxng
    networks:
      - homelab
    ports:
      - 8889:8080
  # https://github.com/modelcontextprotocol/inspector
  # http://ubuntu1:6274/?transport=sse&serverUrl=http://mcp-proxy:8096/servers/home-assistant/sse
  # http://ubuntu1:6274/?transport=sse&serverUrl=http://mcp-proxy:8096/servers/time/sse
  mcp-inspector:
    image: ghcr.io/modelcontextprotocol/inspector
    restart: unless-stopped
    environment:
      ALLOWED_ORIGINS: http://ubuntu1:6274
      HOST: 0.0.0.0
      DANGEROUSLY_OMIT_AUTH: "true"
    ports:
      - 6274:6274 # ui
      - 6277:6277 # api
    networks:
      - homelab
  # https://github.com/sparfenyuk/mcp-proxy
  # http://ubuntu1:8096/status
  mcp-proxy:
    build:
      context: ./mcp-proxy
    restart: unless-stopped
    command: >
      --transport sse
      --port 8096
      --host 0.0.0.0
      --named-server-config /app/config.json
      --pass-environment
    # --debug
    environment:
      API_ACCESS_TOKEN: ${HA_API_ACCESS_TOKEN}
      SEARXNG_URL: http://searxng:8080/
    volumes:
      - ./mcp-proxy/config.json:/app/config.json
      - ./mcp-proxy/memory:/app/memory
      - ./mcp-proxy/basic-memory:/app/basic-memory
    networks:
      - homelab
  # https://github.com/roryeckel/wyoming_openai/
  wyoming-openai:
    image: ghcr.io/roryeckel/wyoming_openai:latest
    environment:
      STT_OPENAI_URL: http://mithras-pc:8001/v1
      STT_MODELS: distil-whisper/distil-large-v3.5-ct2
      # STT_STREAMING_MODELS: distil-whisper/distil-large-v3.5-ct2
      STT_BACKEND: SPEACHES
      TTS_OPENAI_URL: http://mithras-pc:8001/v1
      TTS_MODELS: speaches-ai/Kokoro-82M-v1.0-ONNX
      TTS_BACKEND: SPEACHES
      TTS_SPEED: "1.1"
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    name: homelab

# ---

# wyoming-piper:
#   image: rhasspy/wyoming-piper
#   command: --voice en_US-libritts_r-medium
#   container_name: wyoming-piper
#   restart: unless-stopped
#   hostname: wyoming-piper
#   volumes:
#     - ./wyoming-piper/data:/data
#   ports:
#     - 10200:10200
#   networks:
#     - homelab

# wyoming-whisper:
#   image: rhasspy/wyoming-whisper
#   command:
#     - --model
#     # - medium-int8 # 3-4s
#     # - distil-medium.en # 4-5s
#     # - medium.en # 5-6s
#     # - distil-large-v2 # 8-9s
#     - ellisd/faster-whisper-distil-medium-en-int8 # 3s
#     # - ellisd/faster-whisper-distil-large-v2-en-int8 # 5s
#     - --language
#     - en
#   container_name: wyoming-whisper
#   restart: unless-stopped
#   hostname: wyoming-whisper
#   volumes:
#     - ./wyoming-whisper/data:/data
#   ports:
#     - 10300:10300
#   networks:
#     - homelab

# adguardhome:
#   image: adguard/adguardhome
#   container_name: adguardhome
#   restart: unless-stopped
#   volumes:
#     - ./adguard/work:/opt/adguardhome/work
#     - ./adguard/conf:/opt/adguardhome/conf
#     - /etc/localtime:/etc/localtime:ro
#   ports:
#     - 53:53/tcp
#     - 53:53/udp
#     - 3000:3000
#   user: "${UID}:${GID}"
