services:
  rhasspy:
    image: rhasspy/rhasspy
    container_name: rhasspy
    restart: unless-stopped
    volumes:
      - ./rhasspy/profiles:/profiles
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 12101:12101
    networks:
      - homelab
    command: --user-profiles /profiles --profile en
    user: "${UID}:${GID}"
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9443:9443
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1883:1883
    networks:
      - homelab
    user: "${UID}:${GID}"
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000
    user: "${UID}:${GID}"
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=America/Los_Angeles
      - URL=${DOMAIN}
      - VALIDATION=dns
      - DNSPLUGIN=duckdns
      - EMAIL=${EMAIL}
    volumes:
      - ./swag:/config
      - /etc/localtime:/etc/localtime:ro
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    volumes:
      - ./homeassistant:/config
      - ./tmp:/config/tmp
      - ./swag/etc/letsencrypt:/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
    user: "${UID}:${GID}"
    networks:
      - homelab
  appdaemon:
    image: acockburn/appdaemon:dev
    container_name: appdaemon
    restart: unless-stopped
    volumes:
      - ./appdaemon:/conf
      - ./tmp:/conf/tmp
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5050:5050
    user: "${UID}:${GID}"
    networks:
      - homelab
  zwavejs:
    image: zwavejs/zwave-js-ui
    container_name: zwavejs
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./zwavejs:/usr/src/app/store
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8091:8091
      - 3001:3000 # TODO: remove
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_51300097-if00-port0:/dev/zwave
    user: "${UID}:${GID}"
    group_add:
      - dialout
    networks:
      - homelab
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_fa78108a5586ec11b33feb3719c2d21c-if00-port0:/dev/zigbee
    user: "${UID}:${GID}"
    group_add:
      - dialout
    networks:
      - homelab
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=America/Los_Angeles
      - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  # chatgpt:
  #   image: ghcr.io/m1guelpf/chatgpt-telegram
  #   container_name: chatgpt
  #   restart: unless-stopped
  #   volumes:
  #     - ./chatgpt:/root/.config
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - TELEGRAM_ID=${TELEGRAM_ID}
  #     - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped
    hostname: my-syncthing
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - ./syncthing:/var/syncthing
      - ./swag/etc/letsencrypt:/etc/letsencrypt
      - ./swag/etc/letsencrypt/live/mithras.duckdns.org/cert.pem:/var/syncthing/config/https-cert.pem
      - ./swag/etc/letsencrypt/live/mithras.duckdns.org/privkey.pem:/var/syncthing/config/https-key.pem
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      # - 21027:21027/udp # Receive local discovery broadcasts
networks:
  homelab:
    name: homelab
