services:
  rhasspy:
    image: rhasspy/rhasspy
    container_name: rhasspy
    restart: unless-stopped
    volumes:
      - /home/mithras/homelab/rhasspy/profiles:/profiles
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 12101:12101
    networks:
      - homelab
    command: --user-profiles /profiles --profile en
    user: "${UID}:${GID}"
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mithras/homelab/portainer:/data
    ports:
      - 9443:9443
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - /home/mithras/homelab/mosquitto/config:/mosquitto/config
      - /home/mithras/homelab/mosquitto/data:/mosquitto/data
      - /home/mithras/homelab/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    networks:
      - homelab
    user: "${UID}:${GID}"
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - /home/mithras/homelab/adguard/work:/opt/adguardhome/work
      - /home/mithras/homelab/adguard/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000
    user: "${UID}:${GID}"
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=America/Los_Angeles
      - URL=${DOMAIN}
      - VALIDATION=dns
      - DNSPLUGIN=duckdns
      - EMAIL=${EMAIL}
    volumes:
      - /home/mithras/homelab/swag:/config
      - /etc/localtime:/etc/localtime:ro
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    volumes:
      - /home/mithras/homelab/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /home/mithras/homelab/swag/etc/letsencrypt:/letsencrypt
    ports:
      - 8123:8123
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    user: "${UID}:${GID}"
    networks:
      - homelab
  appdaemon:
    image: acockburn/appdaemon:dev
    container_name: appdaemon
    restart: unless-stopped
    volumes:
      - /home/mithras/homelab/appdaemon:/conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5050:5050
    user: "${UID}:${GID}"
    networks:
      - homelab
networks:
  homelab:
    name: homelab
