x-security-base: &security-base
  restart: unless-stopped
  cap_drop:
    - NET_RAW
    - NET_ADMIN
  security_opt:
    - no-new-privileges:true
x-sandbox-base: &sandbox-base
  <<: *security-base
  # image: sandbox:full
  image: sandbox:agent
  environment:
    PUID: ${UID}
    PGID: ${GID}
    TZ: America/Los_Angeles
    LOG_STDOUT: "true"
x-hermes-base: &hermes-base
  <<: *security-base
  image: hermes-agent
  command: gateway run
  env_file:
    - ./hermes/.env

include:
  - path: litellm/docker-compose.yml
  - path: firecrawl/docker-compose.yml

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1883:1883
    networks:
      - homelab
    user: "${UID}:${GID}"

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      # - PYTHON_FROZEN_MODULES=off # https://docs.python.org/3/using/cmdline.html#envvar-PYTHON_FROZEN_MODULES
    volumes:
      - ./homeassistant:/config
      - ./tmp:/config/tmp
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123 # Web UI
    #   - 5678:5678 # Debug
    privileged: true
    # user: "${UID}:${GID}"
    networks:
      - homelab
    cap_add:
      - NET_ADMIN
      - NET_RAW

  appdaemon:
    image: acockburn/appdaemon:latest
    container_name: appdaemon
    restart: unless-stopped
    volumes:
      - ./appdaemon:/conf
      - ./tmp:/conf/tmp
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5050:5050
    user: "${UID}:${GID}"
    networks:
      - homelab

  zwavejs:
    image: zwavejs/zwave-js-ui
    container_name: zwavejs
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./zwavejs:/usr/src/app/store
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8091:8091
      - 3001:3000
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_51300097-if00-port0:/dev/zwave
    user: "${UID}:${GID}"
    group_add:
      - dialout
    networks:
      - homelab

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_fa78108a5586ec11b33feb3719c2d21c-if00-port0:/dev/zigbee
    user: "${UID}:${GID}"
    group_add:
      - dialout
    networks:
      - homelab

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped
    hostname: my-syncthing
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - ./syncthing:/var/syncthing
    ports:
      # - 3004:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      # - 21027:21027/udp # Receive local discovery broadcasts
    networks:
      - homelab

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
    ports:
      - 81:81 # Admin
      # - 3000:3000 # breaks nginx
      # - 3002:3002 # Open WebUI
      - 8443:8443 # Home Assistant
      - 8384:8384 # Syncthing
      # - 6680:6680 # mpd
      - 8888:8888 # searxng
      # - 8001:8001 # Speaches
      # - 3003:3003 # Vane
      # - 4096:4096 # Opencode
      - 4001:4001 # Litellm (litellm:4000)
      - 9119:9119 # Hermes (mithras)
      - 9120:9120 # Hermes (dina)
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - homelab

  searxng:
    image: docker.io/searxng/searxng
    container_name: searxng
    restart: unless-stopped
    environment:
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
      SEARXNG_SECRET: ${SEARXNG_SECRET}
    volumes:
      - ./searxng:/etc/searxng
    networks:
      - homelab
    ports:
      - 8889:8080

  sandbox-mithras:
    <<: *sandbox-base
    restart: unless-stopped
    volumes:
      # system
      - ./sandbox/config:/config
      - ./sandbox/sshd/mithras-envs.conf:/etc/ssh/sshd_config.d/90-envs.conf
      - ./hermes/tmp:/tmp
      - ./sandbox/gogcli/main:/gogcli
      # hermes
      - ./hermes/mithras:/home/hermes/.hermes:ro
      - ./syncthing/Obsidian/Main/hermes/memories:/home/hermes/.hermes/memories:ro
      - ./syncthing/Obsidian/Main/hermes/skills:/home/hermes/.hermes/skills:ro
      # obsidian
      - ./syncthing/Obsidian/Main:/home/hermes/obsidian
      - ./syncthing/Obsidian/Main/hermes:/home/hermes/obsidian/hermes:ro
    networks:
      - sandbox-main
  sandbox-dina:
    <<: *sandbox-base
    restart: unless-stopped
    volumes:
      # system
      - ./sandbox/config:/config
      - ./sandbox/sshd/dina-envs.conf:/etc/ssh/sshd_config.d/90-envs.conf
      - ./hermes/tmp:/tmp
      - ./sandbox/gogcli/dina:/gogcli
      # hermes
      - ./hermes/dina:/home/hermes/.hermes:ro
      - ./syncthing/Obsidian-dina/main/hermes/memories:/home/hermes/.hermes/memories:ro
      - ./syncthing/Obsidian-dina/main/hermes/skills:/home/hermes/.hermes/skills:ro
      # obsidian
      - ./syncthing/Obsidian-dina/main:/home/hermes/obsidian
      - ./syncthing/Obsidian-dina/main/hermes:/home/hermes/obsidian/hermes:ro
    networks:
      - sandbox-dina
  sandbox-mom:
    <<: *sandbox-base
    restart: unless-stopped
    volumes:
      # system
      - ./sandbox/config:/config
      - ./sandbox/sshd/mom-envs.conf:/etc/ssh/sshd_config.d/90-envs.conf
      - ./hermes/tmp:/tmp
      # hermes
      - ./hermes/dina:/home/hermes/.hermes:ro
    networks:
      - sandbox-mom

  # docker exec -it hermes hermes
  hermes-mithras:
    <<: *hermes-base
    restart: unless-stopped
    environment:
      HERMES_DASHBOARD_BASIC_AUTH_USERNAME: mithras
      HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ${HERMES_DASHBOARD_PASSWORD_MITHRAS}
      HERMES_DASHBOARD_BASIC_AUTH_SECRET: ${HERMES_DASHBOARD_SECRET_MITHRAS}
    volumes:
      - ./hermes/mithras:/opt/data
      - ./hermes/tmp:/tmp
      - ./syncthing/Obsidian/Main/hermes/memories:/opt/data/memories
      - ./syncthing/Obsidian/Main/hermes/skills:/opt/data/skills
    networks:
      - homelab
      - sandbox-main
  hermes-dina:
    <<: *hermes-base
    restart: unless-stopped
    environment:
      HERMES_DASHBOARD_BASIC_AUTH_USERNAME: dina
      HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ${HERMES_DASHBOARD_PASSWORD_DINA}
      HERMES_DASHBOARD_BASIC_AUTH_SECRET: ${HERMES_DASHBOARD_SECRET_DINA}
    volumes:
      - ./hermes/dina:/opt/data
      - ./hermes/tmp:/tmp
      - ./syncthing/Obsidian-dina/main/hermes/memories:/opt/data/memories
      - ./syncthing/Obsidian-dina/main/hermes/skills:/opt/data/skills
    networks:
      - homelab
      - sandbox-dina
  hermes-mom:
    <<: *hermes-base
    restart: unless-stopped
    volumes:
      - ./hermes/mom:/opt/data
      - ./hermes/tmp:/tmp
    networks:
      - homelab
      - sandbox-mom

networks:
  homelab: {}
  sandbox-main: {}
  sandbox-dina: {}
  sandbox-mom: {}
