
include:
  - path: litellm/docker-compose.yml
  - path: firecrawl/docker-compose.yml

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1883:1883
    networks:
      - homelab
    user: "${UID}:${GID}"

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      # - PYTHON_FROZEN_MODULES=off # https://docs.python.org/3/using/cmdline.html#envvar-PYTHON_FROZEN_MODULES
    volumes:
      - ./homeassistant:/config
      - ./tmp:/config/tmp
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123 # Web UI
    #   - 5678:5678 # Debug
    privileged: true
    # user: "${UID}:${GID}"
    networks:
      - homelab
    cap_add:
      - NET_ADMIN
      - NET_RAW

  appdaemon:
    image: acockburn/appdaemon:latest
    container_name: appdaemon
    restart: unless-stopped
    volumes:
      - ./appdaemon:/conf
      - ./tmp:/conf/tmp
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5050:5050
    user: "${UID}:${GID}"
    networks:
      - homelab

  zwavejs:
    image: zwavejs/zwave-js-ui:11.3 # 11.4 is busted
    container_name: zwavejs
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./zwavejs:/usr/src/app/store
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8091:8091
      - 3001:3000
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_51300097-if00-port0:/dev/zwave
    user: "${UID}:${GID}"
    group_add:
      - dialout
    networks:
      - homelab

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_fa78108a5586ec11b33feb3719c2d21c-if00-port0:/dev/zigbee
    user: "${UID}:${GID}"
    group_add:
      - dialout
    networks:
      - homelab

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped
    hostname: my-syncthing
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - ./syncthing:/var/syncthing
    ports:
      # - 3004:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      # - 21027:21027/udp # Receive local discovery broadcasts
    networks:
      - homelab

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
    ports:
      - 81:81 # Admin
      # - 3000:3000 # breaks nginx
      # - 3002:3002 # Open WebUI
      - 8443:8443 # Home Assistant
      - 8384:8384 # Syncthing
      # - 6680:6680 # mpd
      - 8888:8888 # searxng
      # - 8001:8001 # Speaches
      # - 3003:3003 # Vane
      # - 4096:4096 # Opencode
      - 4001:4001 # Litellm (litellm:4000)
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - homelab

  searxng:
    image: docker.io/searxng/searxng
    container_name: searxng
    restart: unless-stopped
    environment:
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
      SEARXNG_SECRET: ${SEARXNG_SECRET}
    volumes:
      - ./searxng:/etc/searxng
    networks:
      - homelab
    ports:
      - 8889:8080

  openclaw:
    # image: ghcr.io/openclaw/openclaw
    image: openclaw:20260612
    restart: unless-stopped
    cap_drop:
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: America/Los_Angeles
    volumes:
      - ./openclaw:/home/node/.openclaw
      # Main
      - ./syncthing/Obsidian/Main/openclaw:/home/node/.openclaw/workspace/main
      - ./syncthing/Obsidian/Main:/home/node/.openclaw/workspace/main/obsidian
      - ./openclaw-workspace/empty:/home/node/.openclaw/workspace/main/obsidian/openclaw
      - ./openclaw-workspace/workspace/main/scrap:/home/node/.openclaw/workspace/main/scrap
      # Dina
      - ./syncthing/Obsidian-dina/main/openclaw:/home/node/.openclaw/workspace/dina
      - ./syncthing/Obsidian-dina/main:/home/node/.openclaw/workspace/dina/obsidian
      - ./openclaw-workspace/empty:/home/node/.openclaw/workspace/dina/obsidian/openclaw
      - ./openclaw-workspace/workspace/dina/scrap:/home/node/.openclaw/workspace/dina/scrap
    ports:
      - 18789:18789 # gateway
      # - 18790:18790 # bridge
      - 8787:8787 # telegram
    networks:
      - homelab
      - openclaw-main
      - openclaw-dina
  openclaw-workspace-main:
    # image: openclaw-workspace:full
    image: openclaw-workspace:agent
    restart: unless-stopped
    cap_drop:
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: America/Los_Angeles
      LOG_STDOUT: "true"
    volumes:
      - ./openclaw-workspace/config:/config
      - ./openclaw-workspace/gogcli/main:/gogcli
      - ./openclaw-workspace/gogcli/main/90-gogenv.conf:/etc/ssh/sshd_config.d/90-gogenv.conf
      - ./openclaw-workspace/90-firecrawl.conf:/etc/ssh/sshd_config.d/90-firecrawl.conf
      - ./syncthing/Obsidian/Main/openclaw:/workspace/openclaw-ssh-agent-main-25bffc4d/workspace
      - ./syncthing/Obsidian/Main:/workspace/openclaw-ssh-agent-main-25bffc4d/workspace/obsidian
      - /tmp/empty:/workspace/openclaw-ssh-agent-main-25bffc4d/workspace/obsidian/openclaw
      - ./openclaw-workspace/workspace/main/scrap:/workspace/openclaw-ssh-agent-main-25bffc4d/workspace/scrap
    networks:
      - openclaw-main
  openclaw-workspace-dina:
    # image: openclaw-workspace:full
    image: openclaw-workspace:agent
    restart: unless-stopped
    cap_drop:
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: America/Los_Angeles
      LOG_STDOUT: "true"
    volumes:
      - ./openclaw-workspace/config:/config
      - ./openclaw-workspace/gogcli/dina:/gogcli
      - ./openclaw-workspace/gogcli/dina/90-gogenv.conf:/etc/ssh/sshd_config.d/90-gogenv.conf
      - ./openclaw-workspace/90-firecrawl.conf:/etc/ssh/sshd_config.d/90-firecrawl.conf
      - ./syncthing/Obsidian-dina/main/openclaw:/workspace/openclaw-ssh-agent-dina-25b7f644/workspace
      - ./syncthing/Obsidian-dina/main:/workspace/openclaw-ssh-agent-dina-25b7f644/workspace/obsidian
      - /tmp/empty:/workspace/openclaw-ssh-agent-dina-25b7f644/workspace/obsidian/openclaw
      - ./openclaw-workspace/workspace/dina/scrap:/workspace/openclaw-ssh-agent-dina-25b7f644/workspace/scrap
    networks:
      - openclaw-dina

networks:
  homelab: {}
  openclaw-main: {}
  openclaw-dina: {}
