model_list:
  - model_name: qwen36-27
    litellm_params:
      litellm_credential_name: pc
      custom_llm_provider: custom_openai
      model: qwen36-27
      tags: ["pc"]
      additional_drop_params: ["reasoning_effort"]
    model_info:
      mode: chat
  - model_name: gemma4-31
    litellm_params:
      litellm_credential_name: pc
      custom_llm_provider: custom_openai
      model: gemma4-31
      tags: ["pc"]
      additional_drop_params: ["reasoning_effort"]
    model_info:
      mode: chat
  - model_name: qwen36-35
    litellm_params:
      litellm_credential_name: ms-s1-max-0
      custom_llm_provider: custom_openai
      model: qwen36-35
      tags: ["ms-s1-max-0"]
      additional_drop_params: ["reasoning_effort"]
    model_info:
      mode: chat
  - model_name: qwen3-0.6-embedding
    litellm_params:
      litellm_credential_name: pc-embedding
      custom_llm_provider: openai_like
      model: Qwen/Qwen3-Embedding-0.6B-GGUF
      tags: ["pc"]
    model_info:
      mode: embedding

credential_list:
  - credential_name: pc
    credential_values:
      api_base: http://192.168.0.2:8080/v1
      api_key: na
    credential_info: {}
  - credential_name: pc-embedding
    credential_values:
      api_base: http://192.168.0.2:8081/v1
      api_key: na
    credential_info: {}
  - credential_name: ms-s1-max-0
    credential_values:
      api_base: http://192.168.0.3:8080/v1
      api_key: na
    credential_info: {}

general_settings:
  always_include_stream_usage: true

# litellm_settings:
#   callbacks:
#     - websearch_interception
#   websearch_interception_params:
#     enabled_providers:
#       - openai
#     search_tool_name: searxng-search

# search_tools:
#   - search_tool_name: searxng-search
#     litellm_params:
#       search_provider: searxng
#       api_base: http://192.168.0.6:8889/

router_settings:
  routing_strategy: simple-shuffle  # `least-busy` doesn't work
  model_group_alias:
    qwen-dense: qwen36-27
    qwen-moe: qwen36-35
    gemma-dense: gemma4-31
    # gemma-moe: 
    # experimental: 
    Qwen3.5-27B: qwen36-27
    qwen-embedding: qwen3-0.6-embedding
