model_list:
  - model_name: qwen38-27
    litellm_params:
      litellm_credential_name: pc
      custom_llm_provider: custom_openai
      model: qwen38-27
      tags: ["pc"]
      allowed_openai_params: ["reasoning_effort"]
    model_info:
      mode: chat
  - model_name: deepseek-v4-flash-0731
    litellm_params:
      litellm_credential_name: gx10
      custom_llm_provider: custom_openai
      model: deepseek-v4-flash-0731
      tags: ["gx10"]
      allowed_openai_params: ["reasoning_effort"]
    model_info:
      mode: chat
  # - model_name: qwen3-4-embedding
  #   litellm_params:
  #     litellm_credential_name: gx10-embedding
  #     custom_llm_provider: openai_like
  #     model: Qwen3-Embedding-4B-Q4_K_M.gguf
  #     tags: ["gx10"]
  #   model_info:
  #     mode: embedding

credential_list:
  - credential_name: pc
    credential_values:
      api_base: http://192.168.1.2:8000/v1
      api_key: na
    credential_info: {}
  - credential_name: gx10
    credential_values:
      api_base: http://192.168.1.8:8000/v1
      api_key: na
    credential_info: {}
  - credential_name: gx10-embedding
    credential_values:
      api_base: http://192.168.1.8:8081/v1
      api_key: na
    credential_info: {}

general_settings:
  always_include_stream_usage: true

# litellm_settings:
#   fallbacks:
#     - "primary": ["secondary"]
#   callbacks:
#     - websearch_interception
#   websearch_interception_params:
#     enabled_providers:
#       - openai
#     search_tool_name: searxng-search

# search_tools:
#   - search_tool_name: searxng-search
#     litellm_params:
#       search_provider: searxng
#       api_base: http://192.168.1.4:8889/

router_settings:
  routing_strategy: simple-shuffle  # `least-busy` doesn't work
  model_group_alias:
    primary: deepseek-v4-flash-0731
    secondary: qwen38-27
    # embedding: qwen3-4-embedding

    o3-mini: qwen38-27 # BUG: https://github.com/firecrawl/firecrawl/pull/3332
