[qwen35-27]
model = /download/qwen3.5-27/Qwen3.5-27B-UD-Q5_K_XL.gguf
mmproj = /download/qwen3.5-27/mmproj-BF16.gguf
ctx-size = 350000
fit-target = 4096,1024
cache-type-k = bf16
cache-type-v = bf16
parallel = 2

; model-draft = /download/qwen3.5-0.8/Qwen3.5-0.8B-UD-Q5_K_XL.gguf
; device-draft = CUDA0
; gpu-layers-draft = all
; draft-max = 3
; draft-min = 1
; ctx-size-draft = 30000
; cache-type-k-draft = bf16
; cache-type-v-draft = bf16


[none]
