# https://www.home-assistant.io/integrations/default_config/
backup:
config:
frontend:
hardware:
history:
homeassistant_alerts:
logbook:
map:
mobile_app:
my:
person:
stream:
sun:
system_health:
zone: !include zone.yaml
# bluetooth:

homeassistant:
  external_url: !secret external_url
  internal_url: https://ubuntu1:8123/
  latitude: !secret latitude
  longitude: !secret longitude
  country: US
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/tmp

recorder: !include recorder.yaml

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

device_tracker:
  - platform: google_maps
    username: !secret location_account
    scan_interval: 30

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: memory_use
      - type: memory_free
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: processor_use
      - type: last_boot

switch:
  - platform: wake_on_lan
    mac: !secret mithras_desktop_mac
    name: Mithras Desktop
    host: 192.168.0.2
    broadcast_address: 192.168.0.255

telegram_bot:
  - platform: webhooks
    parse_mode: markdown
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_mithras
      - !secret telegram_state_chat_mithras
      - !secret telegram_state_chat_diana
      - !secret telegram_debug_chat

wake_on_lan:

input_select:
  security_override:
    name: Security Override
    options:
      - Auto
      - Armed Away
      - Armed Home
      - Armed Sleep
      - Disarmed
    initial: Auto
    icon: mdi:shield-home

input_boolean:
  sleep:
    name: Sleep
    icon: mdi:sleep
  fan:
    name: Fan
    icon: mdi:fan
  tv:
    name: Samsung Smart TV
    icon: mdi:television

lovelace:
  mode: yaml
  resources:
    # https://github.com/thomasloven/lovelace-auto-entities
    - url: /local/ui-lovelace/auto-entities/auto-entities.js
      type: module

appdaemon_app:

intent:
intent_script: !include intent_script.yaml
# conversation:
#   intents:
#     Test:
#       - Test
