# https://www.home-assistant.io/integrations/default_config/
backup:
config:
frontend:
hardware:
history:
homeassistant_alerts:
logbook:
mobile_app:
my:
person:
stream:
sun:
system_health:
zone: !include zone.yaml
bluetooth:
media_source:
assist_pipeline:

homeassistant:
  external_url: !secret external_url
  internal_url: https://ubuntu1:8443/
  latitude: !secret latitude
  longitude: !secret longitude
  country: US
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/tmp

# debugpy:
#   start: false

recorder: !include recorder.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/24

device_tracker:
  - platform: google_maps
    username: !secret location_account
    scan_interval: 30

switch:
  - platform: wake_on_lan
    mac: !secret mithras_desktop_mac
    name: Mithras Desktop
    host: 192.168.0.2
    broadcast_address: 192.168.0.255

telegram_bot:
  - platform: webhooks
    parse_mode: markdown
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      # - !secret telegram_mithras
      - !secret telegram_debug_chat

wake_on_lan:

input_select:
  security_override:
    name: Security Override
    options:
      - Auto
      - Armed Away
      - Armed Home
      - Armed Sleep
      - Disarmed
    initial: Auto
    icon: mdi:shield-home

input_boolean:
  sleep:
    name: Sleep
    icon: mdi:sleep
  tv:
    name: Samsung Smart TV
    icon: mdi:television
  ac_living_room:
    name: AC Living Room
    icon: mdi:air-conditioner
  ac_master_bedroom:
    name: AC Master Bedroom
    icon: mdi:air-conditioner

lovelace:
  mode: yaml
  resources:
    # https://github.com/thomasloven/lovelace-auto-entities
    - url: /local/ui-lovelace/auto-entities/auto-entities.js
      type: module

appdaemon_app:

conversation:
  # intents:
  #   Test:
  #     - Test
intent_script:
  # Test:
  #   speech:
  #     text: Test
