x-gpu-all: &gpu-all
  runtime: nvidia
  devices:
    - nvidia.com/gpu=all
x-gpu-0: &gpu-0
  runtime: nvidia
  devices:
    - nvidia.com/gpu=0
x-gpu-1: &gpu-1
  runtime: nvidia
  devices:
    - nvidia.com/gpu=1

services:
  llama-pc:
    <<: [*gpu-all]
    restart: unless-stopped
    image: llama:server-cuda
    # --models-preset /app/config.ini
    # --models-max 1
    command: >
      --host 0.0.0.0
      --port 8080
      --offline

      --threads 16
      -ngl all
      --no-mmap
      --prio 2
      --prio-batch 2

      --flash-attn on
      --jinja
      --cache-ram 32768
      --cache-reuse 256
      --no-kv-unified

      --model /download/qwen3.6-27-mtp/Qwen3.6-27B-UD-Q5_K_XL.gguf
      --mmproj /download/qwen3.6-27-mtp/mmproj-BF16.gguf
      -dev CUDA0,CUDA1
      --ctx-size 524288
      --tensor-split 100,55
      --cache-type-k q8_0
      --cache-type-v q8_0
      --parallel 2
      --spec-type draft-mtp
      --spec-draft-n-max 2

      --temp 1.0
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 1.5
      --repeat-penalty 1.0
      --reasoning-budget 4096
      --reasoning-budget-message ". Okay enough thinking. Let's just jump to it."
      --chat-template-kwargs "{\"preserve_thinking\": true}"
    volumes:
      - ./llama/config-pc.ini:/app/config.ini
      - ./download/download:/download
    network_mode: host

  vllm-gb10:
    <<: [*gpu-all]
    image: vllm/vllm-openai:latest-aarch64-cu130-ubuntu2404
    restart: unless-stopped
    command: >
      Qwen/Qwen3.6-35B-A3B-FP8
        --host 0.0.0.0
        --port 8000
        --gpu-memory-utilization 0.85
        --max-num-seqs 3
        --max-num-batched-tokens 32768
        --kv-cache-dtype fp8
        --enable-prefix-caching
        --enable-auto-tool-choice
        --trust-remote-code
        --load-format fastsafetensors
        --attention-backend flashinfer

        --max-model-len 262144
        --reasoning-parser qwen3
        --tool-call-parser qwen3_coder
        --speculative-config '{"method":"mtp","num_speculative_tokens":2}'
        --default-chat-template-kwargs '{"preserve_thinking":true}'
        --override-generation-config '{"temperature":0.6,"top_p":0.95,"top_k":20,"min_p":0.0,"presence_penalty":0.0,"repetition_penalty":1.0}'
        --stream-interval 10
    # --max-num-seqs 8 # https://github.com/vllm-project/vllm/issues/35288
    volumes:
      - ./vllm/cache:/root/.cache
    network_mode: host
    environment:
      PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True
      OMP_NUM_THREADS: '8'
      # VLLM_USE_FLASHINFER_MOE_FP8: '1'

  llama-gb10-embedding:
    <<: [*gpu-all]
    restart: unless-stopped
    image: llama:server-cuda
    command: >
      --host 0.0.0.0
      --port 8081
      --embedding
      --model /download/Qwen3-Embedding-4B-GGUF/Qwen3-Embedding-4B-Q4_K_M.gguf
      --ctx-size 12288
      --parallel 4
    volumes:
      - ./download/download:/download
    ports:
      - 8081:8081

  # https://github.com/speaches-ai/speaches/
  # http://localhost:8001/
  # http://localhost:8001/v1/registry?task=text-to-speech
  # + curl http://localhost:8001/v1/models/speaches-ai/Kokoro-82M-v1.0-ONNX -X POST
  # http://localhost:8001/v1/registry?task=automatic-speech-recognition
  # + curl http://localhost:8001/v1/models/Systran/faster-whisper-large-v3 -X POST
  # + curl http://localhost:8001/v1/models/distil-whisper/distil-large-v3.5-ct2 -X POST
  speaches-pc:
    <<: [*gpu-1]
    # image: ghcr.io/speaches-ai/speaches:latest-cuda
    image: speaches
    # image: speaches
    restart: unless-stopped
    environment:
      UVICORN_PORT: "8001"
      # ENABLE_UI: "False"
      TTL: "-1"
      # WHISPER__USE_BATCHED_MODE: "true"
    volumes:
      - ./speaches/cache:/home/ubuntu/.cache/huggingface/hub
    ports:
      - 8001:8001
