x-gpu-all: &gpu-all
  runtime: nvidia
  devices:
    - nvidia.com/gpu=all
x-gpu-0: &gpu-0
  runtime: nvidia
  devices:
    - nvidia.com/gpu=0
x-gpu-1: &gpu-1
  runtime: nvidia
  devices:
    - nvidia.com/gpu=1

x-ds-common: &ds-common
  # restart: unless-stopped
  entrypoint: bash
  command:
    - -c
    - >
      exec vllm serve deepseek-ai/DeepSeek-V4-Flash-0731 \
        --gpu-memory-utilization 0.85 \
        --max-num-seqs 8 \
        --max-num-batched-tokens 8192 \
        --max-cudagraph-capture-size 32 \
        \
        --distributed-executor-backend mp \
        --tensor-parallel-size 2 \
        --nnodes 2 --node-rank $$NODE_RANK \
        --master-addr 192.168.100.1 --master-port 25000 \
        \
        $( [ "$$NODE_RANK" = "0" ] && printf -- '--host 0.0.0.0 --port 8000' || printf -- '--headless' ) \
        --stream-interval 10 \
        --served-model-name deepseek-v4-flash-0731 \
        \
        --enable-prefix-caching \
        --enable-chunked-prefill \
        --enable-auto-tool-choice \
        --trust-remote-code \
        --no-scheduler-reserve-full-isl \
        --moe-backend flashinfer_b12x \
        --attention-backend FLASHINFER_MLA_SPARSE_DSV4 \
        --kv-cache-dtype fp8_ds_mla \
        \
        --max-model-len 262144 \
        --tokenizer-mode deepseek_v4 \
        --reasoning-parser deepseek_v4 \
        --tool-call-parser deepseek_v4 \
        --default-chat-template-kwargs '{"thinking":true,"reasoning_effort":"high"}' \
        --reasoning-config '{"reasoning_parser":"deepseek_v4","reasoning_start_str":"","reasoning_end_str":""}' \
        --speculative-config '{"method":"dspark","num_speculative_tokens":3,"draft_sample_method":"probabilistic"}' \
        --generation-config vllm
  # ---
  # max-cudagraph-capture-size = max-num-seqs * (num_speculative_tokens + 1)
  # kv-cache-dtype = nvfp4_ds_mla: GPU KV cache size: 1,260,108 tokens
  # kv-cache-dtype = fp8_ds_mla: GPU KV cache size: 840,494 tokens
  volumes:
    - ./vllm/cache:/root/.cache
  runtime: nvidia
  devices:
    - nvidia.com/gpu=all
    - /dev/infiniband:/dev/infiniband
  network_mode: host
  shm_size: 64gb
  ulimits:
    memlock: -1
x-ds-env: &ds-env
  # Network
  NCCL_NET: IB
  NCCL_IB_HCA: rocep1s0f0,roceP2p1s0f0
  NCCL_SOCKET_IFNAME: enp1s0f0np0,enP2p1s0f0np0
  NCCL_IB_GID_INDEX: "3"
  NCCL_IGNORE_CPU_AFFINITY: "1"
  TP_SOCKET_IFNAME: enp1s0f0np0,enP2p1s0f0np0
  GLOO_SOCKET_IFNAME: enp1s0f0np0,enP2p1s0f0np0
  # NCCL_DEBUG: INFO

  # DGX Spark
  PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True
  TORCH_CUDA_ARCH_LIST: 12.1a
  FLASHINFER_CUDA_ARCH_LIST: 12.1a
  CUTE_DSL_ARCH: sm_121a

  # B12X
  VLLM_USE_B12X_MOE: "1"
  VLLM_B12X_W4A16_FORCE_BLOCKS_PER_SM: "0"
  VLLM_B12X_W4A16_FORCE_BLOCKS_MAX_M: "16"
  VLLM_USE_B12X_WO_PROJECTION: "1"

  # Init
  SAFETENSORS_FAST_GPU: "1"
  DG_JIT_USE_NVRTC: "0"
  # PYTORCH_TUNABLEOP_ENABLED: "1"

  # Runtime
  VLLM_ALLOW_LONG_MAX_MODEL_LEN: "1"
  VLLM_USE_BREAKABLE_CUDAGRAPH: "0"
  VLLM_USE_FLASHINFER_SAMPLER: "1"
  VLLM_TRITON_MLA_SPARSE: "1"

  # DSpark
  VLLM_DSPARK_LOCAL_ARGMAX: "1"
  VLLM_DSPARK_REPLICATE_MARKOV_W1: "1"
  VLLM_DSPARK_GPU_REJECTED_CONTEXT_MASK: "1"
  VLLM_DSPARK_REFERENCE_KV_QUANT_DEQUANT: "0"
  VLLM_DSPARK_HARDWARE_SCHEDULER_EARLY_STOP: "1"

services:
  llama-pc:
    <<: [*gpu-all]
    restart: unless-stopped
    image: llama:server-cuda
    # --models-preset /app/config.ini
    # --models-max 1
    command: >
      --host 0.0.0.0
      --port 8080
      --offline

      --threads 16
      -ngl all
      --no-mmap
      --prio 2
      --prio-batch 2

      --flash-attn on
      --jinja
      --cache-ram 32768
      --cache-reuse 256
      --no-kv-unified

      --model /download/qwen3.6-27-mtp/Qwen3.6-27B-UD-Q5_K_XL.gguf
      --mmproj /download/qwen3.6-27-mtp/mmproj-BF16.gguf
      -dev CUDA0,CUDA1
      --ctx-size 524288
      --tensor-split 100,55
      --cache-type-k q8_0
      --cache-type-v q8_0
      --parallel 2
      --spec-type draft-mtp
      --spec-draft-n-max 2

      --temp 1.0
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 1.5
      --repeat-penalty 1.0
      --reasoning-budget 4096
      --reasoning-budget-message ". Okay enough thinking. Let's just jump to it."
      --chat-template-kwargs "{\"preserve_thinking\": true}"
    volumes:
      - ./llama/config-pc.ini:/app/config.ini
      - ./download/download:/download
    network_mode: host

  llama-gb10-embedding:
    <<: [*gpu-all]
    restart: unless-stopped
    image: llama:server-cuda
    command: >
      --host 0.0.0.0
      --port 8081
      --embedding
      --model /download/Qwen3-Embedding-4B-GGUF/Qwen3-Embedding-4B-Q4_K_M.gguf
      --ctx-size 12288
      --parallel 4
    volumes:
      - ./download/download:/download
    ports:
      - 8081:8081

  speaches-pc:
    # https://github.com/speaches-ai/speaches/
    # http://localhost:8001/
    # http://localhost:8001/v1/registry?task=text-to-speech
    # + curl http://localhost:8001/v1/models/speaches-ai/Kokoro-82M-v1.0-ONNX -X POST
    # http://localhost:8001/v1/registry?task=automatic-speech-recognition
    # + curl http://localhost:8001/v1/models/Systran/faster-whisper-large-v3 -X POST
    # + curl http://localhost:8001/v1/models/distil-whisper/distil-large-v3.5-ct2 -X POST
    <<: [*gpu-1]
    # image: ghcr.io/speaches-ai/speaches:latest-cuda
    image: speaches
    # image: speaches
    restart: unless-stopped
    environment:
      UVICORN_PORT: "8001"
      # ENABLE_UI: "False"
      TTL: "-1"
      # WHISPER__USE_BATCHED_MODE: "true"
    volumes:
      - ./speaches/cache:/home/ubuntu/.cache/huggingface/hub
    ports:
      - 8001:8001

  vllm-gb10-ds-head:
    <<: [*ds-common]
    # image: vllm/vllm-openai:latest-aarch64-cu130-ubuntu2404
    # image: ghcr.io/spark-arena/dgx-vllm-eugr-nightly-tf5
    image: ghcr.io/anemll/dspark-vllm-gx10:0.1.1
    # image: aidendle94/sparkrun-vllm-ds4-gb10:production-3.75
    environment:
      <<: *ds-env
      VLLM_HOST_IP: 192.168.100.1
      NODE_RANK: "0"

  vllm-gb10-ds-worker:
    <<: [*ds-common]
    # image: vllm/vllm-openai:latest-aarch64-cu130-ubuntu2404
    # image: ghcr.io/spark-arena/dgx-vllm-eugr-nightly-tf5
    image: ghcr.io/anemll/dspark-vllm-gx10:0.1.1
    # image: aidendle94/sparkrun-vllm-ds4-gb10:production-3.75
    environment:
      <<: *ds-env
      VLLM_HOST_IP: 192.168.100.2
      NODE_RANK: "1"
