# P1
#   - memory (rag/embeding/reranker, data/memories)
#   - firecrawl cli + skills
#   - tools/skills (data/skills)
#   - Email
#   - mithras-pc (PC) profile

# P2
#   - mcp: linkedin
#   - Home Assistant
#   - pdf?

_config_version: 33

terminal:
  # ssh -p 2222 -i /opt/data/.ssh/id_rsa linuxserver.io@sandbox-mithras
  # ssh -p 2222 -i /opt/data/.ssh/id_rsa linuxserver.io@sandbox-dina
  backend: ssh
  cwd: ${TERMINAL_CWD}
  file_sync_enabled: false
platforms:
  telegram:
    extra:
      ignore_root_dm: true
telegram:
  reactions: true
display:
  interface: tui
  busy_input_mode: steer # interrupt | queue | steer
  streaming: true
  platforms:
    telegram:
      streaming: false # `true` causes duplicated/intemediate messages
kanban:
  max_in_progress: 2
skills: {}
plugins:
  enabled:
    - hermes-lcm
browser:
  cdp_url: ws://localhost:9222
# agent:
#   enabled_toolsets: []
#   disabled_toolsets: []
memory:
  provider: byterover
  memory_char_limit: 5000
  user_char_limit: 2500
context:
  engine: lcm
session_reset:
  mode: none
platform_toolsets:
  cli:
    - browser
    - clarify
    - code_execution
    - context_engine
    - cronjob
    - delegation
    - file
    - memory
    - session_search
    - skills
    - terminal
    - todo
    - tts
    - vision
    - web
    # - homeassistant
    # - image_gen
    # - kanban
  telegram:
    - browser
    - clarify
    - code_execution
    - context_engine
    - cronjob
    - delegation
    - file
    - memory
    - session_search
    - skills
    - terminal
    - todo
    - tts
    - vision
    - web
    # - homeassistant
    # - image_gen
    # - kanban
  cron:
    - browser
    - file
    - terminal
    - web
    # - kanban
security:
  tirith_enabled: true
  tirith_fail_open: false
  allow_lazy_installs: false
approvals:
  mode: smart # manual | smart
  destructive_slash_confirm: false
timezone: America/Los_Angeles
onboarding:
  seen:
    busy_input_prompt: true

model:
  default: qwen36-27
  provider: litellm
providers:
  litellm:
    api: http://litellm:4000
    name: litellm
    api_key: ${LITELLM_API_KEY}
    models:
      qwen36-27:
        context_length: 262144
        supports_vision: true
      gb10-qwen36-27:
        context_length: 262144
    default_model: qwen36-27
auxiliary:
  vision:
    provider: litellm
tts:
  provider: openai
  openai:
    model: speaches-ai/Kokoro-82M-v1.0-ONNX
    voice: af_heart
    speed: 1.25
    base_url: http://mithras-pc:8001/v1
    api_key: na
stt:
  enabled: true
  provider: openai
  openai:
    model: istupakov/parakeet-tdt-0.6b-v3-onnx
    base_url: http://mithras-pc:8001/v1
    api_key: na
